name: Auto Label PR

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  add-label:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number
        id: get_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run_id = context.payload.workflow_run.id;
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'CI',
              per_page: 1,
              filter: 'completed',
              status: 'success'
            });

            const run = runs.workflow_runs.find(run => run.id === run_id);
            const pr_number = run.pull_requests[0].number;

            return pr_number;

      - name: Add automerge Label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ steps.get_pr.outputs.pr_number }};
            const labelToAdd = "automerge";
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              labels: [labelToAdd]
            });
