name: Auto Merge

on:
  workflow_call:
    secrets:
      CI_TOKEN:
        required: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Merge branch
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          git checkout dev
          git checkout -b temp-branch
          git checkout master
          git pull origin master
          git merge temp-branch --no-ff --allow-unrelated-histories || true

      - name: Handle merge conflicts
        if: failure()
        run: |
          echo "Merge conflicts detected. Attempting to resolve..."
          git checkout --ours .
          git add .
          git commit -m "Resolved merge conflicts"

      - name: Push changes
        run: |
          git push origin master
