name: Auto Label PR

on:
  pull_request:
    types: opened

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add automerge Label
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: 'automerge'
