name: Auto Merge

on:
  workflow_call:
    secrets:
      CI_TOKEN:
        required: true

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge PR
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl -s -X PUT \
            -H "Authorization: token $CI_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
            -d '{"commit_title": "Auto-merging PR", "merge_method": "merge"}'
