name: Pull Request Check

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true
env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.7

permissions:
  pull-requests: write
  contents: read
  checks: write

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "API_KEY=${{ secrets.API_KEY }}" > local.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Android Lint
        id: android-lint
        run: ./gradlew lint

      - name: Check and report lint results
        uses: hidakatsuya/action-report-android-lint@v1.2.0
        with:
          result-path: 'app/build/reports/lint-results-debug.xml'

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-tools
        with:
          java: true
          gradle: true
          reviewdog: true

      - name: Ktlint
        id: ktlint
        run: ./gradlew ktlintCheck
        continue-on-error: true

      - name: Comment PR by reviewdog
        run: |
          find ./*/build/reports/ktlint/*/*.xml \
            -type f \
            -exec sh -c "cat {} | reviewdog -f=checkstyle -diff='git diff FETCH_HEAD' -reporter=github-pr-review" \;

      - name: Lint Error Handling
        if: ${{ steps.ktlint.outcome == 'failure' }}
        run: exit 1

