name: Pull Request CI

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The PR number'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  PullRequestCheck:
    uses: ./.github/workflows/call-pull-request-check.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}

  UnitTests:
    uses: ./.github/workflows/call-unit-test.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
