name: Run ktlint

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true

permissions:
  contents: read
  checks: write

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create local.properties
        run: echo "API_KEY=${{ secrets.API_KEY }}" > local.properties

      - name: Execute Gradle check
        run: ./gradlew check || true
        continue-on-error: true

      - name: Upload ktlint errors
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ktlint-errors
          path: app/build/reports/

      - name: Upload ktlint artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-output
          path: 'app/build/ktlint.xml'

    outputs:
      artifact-name: ${{ steps.upload-artifact.outputs.name }}

  danger:
    runs-on: ubuntu-latest
    needs: ktlint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download ktlint artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.ktlint.outputs.artifact-name }}
          path: 'app/build/'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: false

      - name: Restore gradle cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: MeilCli/danger-action@v6
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload danger summary
        uses: actions/upload-artifact@v3
        with:
          name: danger-summary
          path: danger-result.md

      - name: Output danger summary
        run: |
          mkdir -p $RUNNER_TEMP
          cat danger-result.md >> $RUNNER_TEMP/op.md
          echo "::warning file=$RUNNER_TEMP/op.md,line=1,col=1,title=Danger Summary::"