name: Run ktlint

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true

permissions:
  contents: read
  checks: write

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create local.properties
        run: echo "API_KEY=${{ secrets.API_KEY }}" > local.properties

      - name: Execute Gradle check
        run: ./gradlew check || true
        continue-on-error: true