name: Dev Branch CI-CD

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]

concurrency:
  group: dev-branch-ci-cd-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  ci_cd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Static Analysis
        uses: ./.github/workflows/call-static-analysis.yml
        with:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Auto Merge
        if: success()
        uses: pascalgn/automerge-action@v0.16.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
