name: Dev Branch CI CD

# TODO プッシュではなく、プルリクエストの場合は pull_request に変更したい
on:
  push:
    branches:
      - dev  # プッシュ対象のブランチ名

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  PullRequestCheck:
    uses: ./.github/workflows/call-pull-request-check.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}

  UnitTests:
    uses: ./.github/workflows/call-unit-test.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}

  AutoMerge:
    needs: [PullRequestCheck, UnitTests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
