name: Dev Branch CI-CD

on:
  pull_request:
    branches: ["master", "dev"]
    types: [opened, synchronize]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  StaticAnalysis:
    uses: ./.github/workflows/call-static-analysis.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}

  AutoMarge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Auto Merge
        if: success()
        uses: pascalgn/automerge-action@v0.16.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

