name: Pull Request

on:
  push:
    branches:
      - dev  # プッシュ対象のブランチ名

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: create pull request
        id: create-pull-request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PULL_REQUEST_URI=$(gh pr create --base master --head develop --title "Pulling ${{ github.ref }} into master" --body "*An automated PR for syncing changes from ${{ github.ref }} into master*" -l "automerge" --reviewer user-name)
