name: Pull Request

on:
  push:
    branches:
      - dev  # プッシュ対象のブランチ名

jobs:
  CloudList:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Pull Request"
          title: "Pulling ${{ github.ref }} into master"
          body: "*An automated PR for syncing changes from ${{ github.ref }} into master*"
          base: main # プルリクエスト先のブランチ
          labels: automerge
