name: CI

on:
  pull_request:
    branches: [ "master", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

env:
  JAVA_VERSION: 17
jobs:
  Lint:
    uses: ./.github/workflows/call-lint.yml

  UnitTests:
    uses: ./.github/workflows/call-unit-test.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
