name: CI

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  PullRequestCheck:
    uses: ./.github/workflows/call-pull-request-check.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}

  UnitTests:
    uses: ./.github/workflows/call-unit-test.yml
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
